base_url = "https://vladkens.cc"
title = "vladkens.cc"
description = "Practical software engineering notes"
compile_sass = false
build_search_index = false
generate_sitemap = true
generate_feeds = true
feed_filenames = ["atom.xml"]
taxonomies = [{ name = "tags" }]
default_language = "en"
author = "vladkens"

[markdown]
external_links_target_blank = true

[markdown.highlighting]
light_theme = "github-light"
dark_theme = "github-dark"

[extra]
github = "vladkens"
twitter = "uid127"
lang_switch = ["en", "ru"] # display order in lang switcher

[translations]
nav_home = "home"
nav_tags = "tags"
nav_donate = "donate"
nav_rss = "rss"
projects = "Projects"
posts = "Posts"
posted_at = "Posted"
words = "words"
min_read = "min read"
also_read = "Also read on"
tags_label = "Tags"
tags_title = "Tags"
tagged_with = "Posts tagged"
edit_page = "Edit"
view_markdown = "Markdown"
language_switch = "Lang"
reading_time = "Reading time"
not_found = "Nothing here :("
empty_state = "Nothing here?!"
footer = "All rights reserved. Code samples are public domain unless otherwise noted."

[languages.ru]
title = "vladkens.cc"
generate_feeds = false
taxonomies = [{ name = "tags" }]

[languages.ru.translations]
nav_home = "main" # todo: https://github.com/getzola/zola/issues/3161
view_markdown = "Markdown"
language_switch = "Lang"
