name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: taiki-e/install-action@v2
        with:
          tool: zola@0.22.1

      - run: corepack enable && pnpm install --frozen-lockfile
      - run: pnpm run format:check
      - run: pnpm run update-projects
      - run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - run: zola build

      - uses: cloudflare/wrangler-action@v4
        if: github.ref == 'refs/heads/main'
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy public --project-name=vnotes
